-- Target production design only. This project does not claim a Snowflake deployment.
-- Replace database, warehouse, storage integration and stage placeholders locally.

CREATE SCHEMA IF NOT EXISTS ANALYTICS_CURATED;

CREATE OR REPLACE TABLE ANALYTICS_CURATED.DIM_SERVICE (
    SERVICE_KEY NUMBER(10,0) NOT NULL,
    SERVICE_NAME VARCHAR NOT NULL,
    EXECUTIVE_OWNER VARCHAR,
    IS_STUDENT_FACING BOOLEAN,
    PRIMARY KEY (SERVICE_KEY)
);

CREATE OR REPLACE TABLE ANALYTICS_CURATED.DIM_LIFECYCLE_STAGE (
    LIFECYCLE_STAGE_KEY NUMBER(10,0) NOT NULL,
    LIFECYCLE_STAGE VARCHAR NOT NULL,
    PRIMARY KEY (LIFECYCLE_STAGE_KEY)
);

CREATE OR REPLACE TABLE ANALYTICS_CURATED.FACT_CASE (
    CASE_ID VARCHAR NOT NULL,
    SUBMITTED_DATETIME TIMESTAMP_NTZ NOT NULL,
    CLOSED_DATETIME TIMESTAMP_NTZ,
    SERVICE_KEY NUMBER(10,0) NOT NULL,
    TEAM_KEY NUMBER(10,0) NOT NULL,
    CAMPUS_KEY NUMBER(10,0) NOT NULL,
    COHORT_KEY NUMBER(10,0) NOT NULL,
    LIFECYCLE_STAGE_KEY NUMBER(10,0) NOT NULL,
    CATEGORY VARCHAR NOT NULL,
    PRIORITY VARCHAR NOT NULL,
    CURRENT_STATUS VARCHAR NOT NULL,
    RESOLUTION_BUSINESS_HOURS FLOAT,
    RESOLUTION_SLA_BREACHED BOOLEAN,
    REPEAT_CONTACT_14D BOOLEAN,
    HANDOFF_COUNT NUMBER(10,0),
    STAFF_HANDLE_HOURS FLOAT,
    ESTIMATED_COST_AUD NUMBER(18,2),
    SOURCE_EXTRACT_TS TIMESTAMP_NTZ NOT NULL,
    SYNTHETIC_LABEL VARCHAR NOT NULL,
    PRIMARY KEY (CASE_ID)
)
CLUSTER BY (SERVICE_KEY, TO_DATE(SUBMITTED_DATETIME));

CREATE OR REPLACE TABLE ANALYTICS_CURATED.FACT_ACTION_INSIGHT (
    ACTION_ID VARCHAR NOT NULL,
    INSIGHT_DATE DATE NOT NULL,
    SERVICE_KEY NUMBER(10,0),
    ISSUE VARCHAR NOT NULL,
    RECOMMENDED_ACTION VARCHAR NOT NULL,
    SUGGESTED_OWNER_TEAM_KEY NUMBER(10,0),
    SAMPLE_SIZE NUMBER(10,0),
    BASELINE_VALUE FLOAT,
    TARGET_VALUE FLOAT,
    ACTUAL_VALUE FLOAT,
    ACTION_STATUS VARCHAR,
    NEXT_REVIEW_DATE DATE,
    SYNTHETIC_LABEL VARCHAR NOT NULL,
    PRIMARY KEY (ACTION_ID)
);

-- In production, load through external stages and COPY INTO with rejected-row capture,
-- then run source-to-target reconciliation before publishing to Power BI.

